### ISSUE TITLE
[Solved Bug] Shader's rendering layer issue only in 2022.1

### ISSUE THREAD

**Issue by jiaozi158** [Unity-China/cn.unity.hairfx.urp#2]
URP still uses **GetMeshRenderingLightLayer()** in 2022.1, [this](https://github.com/Unity-China/cn.unity.hairfx.urp/blob/0d6f17e9647430f92e51a3bd4beec39726bd07d7/Editor/ShaderGraph/UniversalPipeline/PhysicalHair/Includes/MarschnerHairBSDF.hlsl#L324) causes a shader compiling error.

To fix this, increase the version from "> 202210" to ">= 202220". (including beta versions)

![2022-1-RenderingLayer](https://user-images.githubusercontent.com/62869447/190670961-406536fe-315e-4020-be26-122d705d36c6.jpg)

**Comment by jiaozi158** [comment]
By the way, looks awesome!🎉

![HairSample](https://user-images.githubusercontent.com/62869447/190673979-bdb076d4-78b6-429d-8918-e27cd5055c06.png)

**Comment by michael430unity** [comment]
[Updated ](https://github.com/Unity-China/cn.unity.hairfx.urp/commit/bbb80d9f95e2be2e13c3ee5efa01735b275f3a22) the UNITY_VERSION code to 202220
