### ISSUE TITLE
Unity 2022.3 版本 MarschnerHairForwardPass.hlsl 第77行少个)，这个提交代码之前都不测试一下的吗？

### ISSUE THREAD

**Issue by Qither** [Unity-China/cn.unity.hairfx.urp#5]
![YQSJJRXN64IE@KT ~(I 6Y](https://github.com/Unity-China/cn.unity.hairfx.urp/assets/116541123/f8e42ac3-93cd-4827-a099-4facc2254da8)

**Comment by michael430** [comment]
Thanks for the error report, Now we fixed the codes and updated to Editor version 2023
